/* Autogenerated code */

export interface Config {
  apps: {
    faucet: {
      port: number;
      useCachingInterceptor: boolean;
      gatewayUrl: string;
      jwtSecret: string;
      recaptchaSecret: string;
      hrp: string;
      faucetPrivateKeyMode: string;
      faucetMnemonic: string;
      faucetPemPath: string;
      faucetPemIndex: number;
      faucetAmount: string;
      faucetToken: string;
      faucetTokenAmount: string;
      faucetRecaptchaSecret: string;
      faucetRecaptchaBypass: boolean;
      faucetCooldownSameAddressInSec: number;
    };
  };
  libs: {
    common: {
      network: "devnet" | "testnet" | "mainnet" | "custom";
      urls: {
        api: string;
      };
      database: {
        host: string;
        port: number;
        username?: string;
        password?: string;
        name: string;
        tlsAllowInvalidCertificates: boolean;
      };
      redis: {
        host: string;
        port: number;
      };
      nativeAuth: {
        maxExpirySeconds: number;
        acceptedOrigins: string[];
      };
      security: {
        admins: string[];
      };
      rateLimiterSecret?: string;
      keepAliveAgent: {
        enabled: boolean;
      };
      keepAliveTimeout: {
        downstream: number;
        upstream: number;
      };
      useCachingInterceptor?: boolean;
    };
  };
}
